default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: wants_prototype_development
  socket: /tmp/mysql.sock  # 開発環境用のソケット設定
  host: localhost

test:
  <<: *default
  database: wants_prototype_test
  socket: /tmp/mysql.sock  # テスト環境用のソケット設定
  host: localhost

production:
  <<: *default
  database: wants_prototype_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock  # EC2用のソケット設定